# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xu/Desktop/JIAOFU

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xu/Desktop/JIAOFU

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xu/Desktop/JIAOFU/CMakeFiles /home/xu/Desktop/JIAOFU/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xu/Desktop/JIAOFU/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImageProcessing

# Build rule for target.
ImageProcessing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImageProcessing
.PHONY : ImageProcessing

# fast build rule for target.
ImageProcessing/fast:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/build
.PHONY : ImageProcessing/fast

adjust.o: adjust.cpp.o

.PHONY : adjust.o

# target to build an object file
adjust.cpp.o:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/adjust.cpp.o
.PHONY : adjust.cpp.o

adjust.i: adjust.cpp.i

.PHONY : adjust.i

# target to preprocess a source file
adjust.cpp.i:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/adjust.cpp.i
.PHONY : adjust.cpp.i

adjust.s: adjust.cpp.s

.PHONY : adjust.s

# target to generate assembly for a file
adjust.cpp.s:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/adjust.cpp.s
.PHONY : adjust.cpp.s

gridalignment.o: gridalignment.cpp.o

.PHONY : gridalignment.o

# target to build an object file
gridalignment.cpp.o:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/gridalignment.cpp.o
.PHONY : gridalignment.cpp.o

gridalignment.i: gridalignment.cpp.i

.PHONY : gridalignment.i

# target to preprocess a source file
gridalignment.cpp.i:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/gridalignment.cpp.i
.PHONY : gridalignment.cpp.i

gridalignment.s: gridalignment.cpp.s

.PHONY : gridalignment.s

# target to generate assembly for a file
gridalignment.cpp.s:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/gridalignment.cpp.s
.PHONY : gridalignment.cpp.s

image_processing.o: image_processing.cpp.o

.PHONY : image_processing.o

# target to build an object file
image_processing.cpp.o:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/image_processing.cpp.o
.PHONY : image_processing.cpp.o

image_processing.i: image_processing.cpp.i

.PHONY : image_processing.i

# target to preprocess a source file
image_processing.cpp.i:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/image_processing.cpp.i
.PHONY : image_processing.cpp.i

image_processing.s: image_processing.cpp.s

.PHONY : image_processing.s

# target to generate assembly for a file
image_processing.cpp.s:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/image_processing.cpp.s
.PHONY : image_processing.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/main.cpp.s
.PHONY : main.cpp.s

sorting.o: sorting.cpp.o

.PHONY : sorting.o

# target to build an object file
sorting.cpp.o:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/sorting.cpp.o
.PHONY : sorting.cpp.o

sorting.i: sorting.cpp.i

.PHONY : sorting.i

# target to preprocess a source file
sorting.cpp.i:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/sorting.cpp.i
.PHONY : sorting.cpp.i

sorting.s: sorting.cpp.s

.PHONY : sorting.s

# target to generate assembly for a file
sorting.cpp.s:
	$(MAKE) -f CMakeFiles/ImageProcessing.dir/build.make CMakeFiles/ImageProcessing.dir/sorting.cpp.s
.PHONY : sorting.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ImageProcessing"
	@echo "... adjust.o"
	@echo "... adjust.i"
	@echo "... adjust.s"
	@echo "... gridalignment.o"
	@echo "... gridalignment.i"
	@echo "... gridalignment.s"
	@echo "... image_processing.o"
	@echo "... image_processing.i"
	@echo "... image_processing.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sorting.o"
	@echo "... sorting.i"
	@echo "... sorting.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

